server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user_service?useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: userservice

#mybatis plus
mybatis-plus:
  type-aliases-package: com.example.userservice.entity
  mapper-locations: mapper/I*Mapper.xml

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka

logging:
  level:
    com.example: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
