server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/order_service?useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  # 给服务取名
  application:
    name: orderservice

#mybatis plus
mybatis-plus:
  type-aliases-package: com.example.orderservice.entity
  mapper-locations: mapper/I*Mapper.xml

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    # 打开eureka客户端，不再用注解形式
    enabled: true

logging:
  level:
    com.example: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
